spring.application.name=FoodTrucks

#SpringDoc OpenApi 3.1 & Swagger 3
springdoc.swagger-ui.path=/docs-FoodTrucks.html
springdoc.api-docs.path=/docs-FoodTrucks
springdoc.packages-to-scan=wiskow.example.FoodTrucks.controllers
